name: dev_documentation
services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dev_documentation
    volumes:
      - pgdata:/bitnami/postgresql
  redis:
    image: redis:8.0-rc1
    restart: always
    command: redis-server
    ports:
      - "6379:6379"
  traefik:
     image: traefik:v3.4
     ports:
       - "80:80"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: dev_documentation
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db
  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge

volumes:
  pgdata: